# Generated by Django 4.1.1 on 2022-09-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0003_alter_aluno_id_alter_curso_id_alter_matricula_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="foto",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
